export const AGREGAR_TAREA_TODO = 'AGREGAR_TAREA_TODO';
export const AGREGAR_TAREA_TODO_EXITO = 'AGREGAR_TAREA_TODO_EXITO';
export const AGREGAR_TAREA_TODO_ERROR = 'AGREGAR_TAREA_TODO_ERROR';

export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ELIMINAR_TAREA_EXITO = 'ELIMINAR_TAREA_EXITO';
export const ELIMINAR_TAREA_ERROR = 'AGREGAR_TAREA_TODO_ERROR';

export const FILTRAR_ALP = 'FILTRAR_ALP';
export const FILTRAR_ALP_EXITO = 'FILTRAR_ALP_EXITO';
export const FILTRAR_ALP_ERROR = 'FILTRAR_ALP_ERROR';

export const FILTRAR_PARABOLA = 'FILTRAR_PARABOLA';
export const FILTRAR_PARABOLA_EXITO = 'FILTRAR_PARABOLA_EXITO';
export const FILTRAR_PARABOLA_ERROR = 'FILTRAR_PARABOLA_ERROR';

export const FILTRAR_NORMAL = 'FILTRAR_NORMAL';
export const FILTRAR_NORMAL_EXITO = 'FILTRAR_NORMAL_EXITO';
export const FILTRAR_NORMAL_ERROR = 'FILTRAR_NORMAL_ERROR';

export const FILTRAR_NERD = 'FILTRAR_NERD';
export const FILTRAR_NERD_EXITO = 'FILTRAR_NERD_EXITO';
export const FILTRAR_NERD_ERROR = 'FILTRAR_NERD_ERROR';